# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import math

import grpc

import sqrt_pb2 as sqrt__pb2


class SqrtStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sqrt = channel.unary_unary(
                '/sqrt.Sqrt/Sqrt',
                request_serializer=sqrt__pb2.Number.SerializeToString,
                response_deserializer=sqrt__pb2.Number.FromString,
                )


class SqrtServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sqrt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        return sqrt__pb2.Number(value=math.sqrt(request.value))


def add_SqrtServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.Sqrt,
                    request_deserializer=sqrt__pb2.Number.FromString,
                    response_serializer=sqrt__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sqrt.Sqrt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sqrt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sqrt.Sqrt/Sqrt',
            sqrt__pb2.Number.SerializeToString,
            sqrt__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
