import grpc
import random

# import classes generated by grpc tools
import std_pb2_grpc, std_pb2

SERVER_ADDRESS = 'localhost'
SERVER_PORT = 5000

# open a gRPC channel
channel = grpc.insecure_channel(f'{SERVER_ADDRESS}:{SERVER_PORT}')

# create a client
stub = std_pb2_grpc.StandardDeviationStub(channel)

# create numbers iterator (request sequence)
numbers = iter([std_pb2.Number(value=random.random()) for i in range(random.randint(0, 100))])

# make the call to grpc server
response = stub.StandardDeviation(numbers)

# print result
print("Standard deviation is:", response.value)
