# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multipliers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11multipliers.proto\x12\x0bmultipliers\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\x32K\n\x0bMultipliers\x12<\n\x0cListFeatures\x12\x13.multipliers.Number\x1a\x13.multipliers.Number\"\x00\x30\x01\x62\x06proto3')



_NUMBER = DESCRIPTOR.message_types_by_name['Number']
Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'multipliers_pb2'
  # @@protoc_insertion_point(class_scope:multipliers.Number)
  })
_sym_db.RegisterMessage(Number)

_MULTIPLIERS = DESCRIPTOR.services_by_name['Multipliers']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=34
  _NUMBER._serialized_end=57
  _MULTIPLIERS._serialized_start=59
  _MULTIPLIERS._serialized_end=134
# @@protoc_insertion_point(module_scope)
