# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import multipliers_pb2 as multipliers__pb2


class MultipliersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFeatures = channel.unary_stream(
                '/multipliers.Multipliers/ListFeatures',
                request_serializer=multipliers__pb2.Number.SerializeToString,
                response_deserializer=multipliers__pb2.Number.FromString,
                )


class MultipliersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultipliersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFeatures,
                    request_deserializer=multipliers__pb2.Number.FromString,
                    response_serializer=multipliers__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multipliers.Multipliers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Multipliers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/multipliers.Multipliers/ListFeatures',
            multipliers__pb2.Number.SerializeToString,
            multipliers__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
