# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnumber.proto\"%\n\x13StreamingMaxRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"&\n\x14StreamingMaxResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32W\n\x12\x43\x61lculationService\x12\x41\n\x0cstreamingMax\x12\x14.StreamingMaxRequest\x1a\x15.StreamingMaxResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_STREAMINGMAXREQUEST = DESCRIPTOR.message_types_by_name['StreamingMaxRequest']
_STREAMINGMAXRESPONSE = DESCRIPTOR.message_types_by_name['StreamingMaxResponse']
StreamingMaxRequest = _reflection.GeneratedProtocolMessageType('StreamingMaxRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGMAXREQUEST,
  '__module__' : 'number_pb2'
  # @@protoc_insertion_point(class_scope:StreamingMaxRequest)
  })
_sym_db.RegisterMessage(StreamingMaxRequest)

StreamingMaxResponse = _reflection.GeneratedProtocolMessageType('StreamingMaxResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGMAXRESPONSE,
  '__module__' : 'number_pb2'
  # @@protoc_insertion_point(class_scope:StreamingMaxResponse)
  })
_sym_db.RegisterMessage(StreamingMaxResponse)

_CALCULATIONSERVICE = DESCRIPTOR.services_by_name['CalculationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMINGMAXREQUEST._serialized_start=16
  _STREAMINGMAXREQUEST._serialized_end=53
  _STREAMINGMAXRESPONSE._serialized_start=55
  _STREAMINGMAXRESPONSE._serialized_end=93
  _CALCULATIONSERVICE._serialized_start=95
  _CALCULATIONSERVICE._serialized_end=182
# @@protoc_insertion_point(module_scope)
