# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import number_pb2 as number__pb2


class CalculationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.streamingMax = channel.stream_stream(
                '/number.CalculationService/streamingMax',
                request_serializer=number__pb2.StreamingMaxRequest.SerializeToString,
                response_deserializer=number__pb2.StreamingMaxResponse.FromString,
                )


class CalculationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def streamingMax(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'streamingMax': grpc.stream_stream_rpc_method_handler(
                    servicer.streamingMax,
                    request_deserializer=number__pb2.StreamingMaxRequest.FromString,
                    response_serializer=number__pb2.StreamingMaxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'number.CalculationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def streamingMax(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/number.CalculationService/streamingMax',
            number__pb2.StreamingMaxRequest.SerializeToString,
            number__pb2.StreamingMaxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
