# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\'\n\x17StreamingMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x18StreamingMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2a\n\x10MessagingService\x12M\n\x10streamingMessage\x12\x18.StreamingMessageRequest\x1a\x19.StreamingMessageResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_STREAMINGMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['StreamingMessageRequest']
_STREAMINGMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['StreamingMessageResponse']
StreamingMessageRequest = _reflection.GeneratedProtocolMessageType('StreamingMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGMESSAGEREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:StreamingMessageRequest)
  })
_sym_db.RegisterMessage(StreamingMessageRequest)

StreamingMessageResponse = _reflection.GeneratedProtocolMessageType('StreamingMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGMESSAGERESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:StreamingMessageResponse)
  })
_sym_db.RegisterMessage(StreamingMessageResponse)

_MESSAGINGSERVICE = DESCRIPTOR.services_by_name['MessagingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMINGMESSAGEREQUEST._serialized_start=17
  _STREAMINGMESSAGEREQUEST._serialized_end=56
  _STREAMINGMESSAGERESPONSE._serialized_start=58
  _STREAMINGMESSAGERESPONSE._serialized_end=98
  _MESSAGINGSERVICE._serialized_start=100
  _MESSAGINGSERVICE._serialized_end=197
# @@protoc_insertion_point(module_scope)
